name: Build

on:
  workflow_run:
    workflows:
      - Testing
    types:
      - completed

jobs:
  python-package:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install twine jinja2

    - name: Build Python package
      run: |
        python -c 'import jinja2;jinja2.Template(open("setup.j2").read()).stream(version="${{ steps.pkg_version.outputs.data }}").dump("setup.py")'
        python setup.py sdist bdist_wheel

  docker-image:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile -t pdns-protobuf-receiver