name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install dnsdist
      run: |
        sudo apt-get install -y dnsdist net-tools

    - name: Configure dnsdist to activate protobuf
      run: |
        sudo systemctl stop dnsdist
        sudo cp -rf tests/dnsdist.conf /etc/dnsdist/
        sudo cat /etc/dnsdist/dnsdist.conf
        sudo mkdir -p /var/run/dnsdist
        sudo chown _dnsdist._dnsdist /var/run/dnsdist/
        sudo systemctl start dnsdist
        sudo systemctl status dnsdist
        sudo netstat -anp | grep dnsdist
        
    - name: Run Python tests 
      run: |
        sudo python3 -m pip install protobuf
        sudo python3 -m pip install --upgrade dnspython
        sudo python3 -m unittest tests.test_stdout -v
        sudo python3 -m unittest tests.test_usage -v
